### ISSUE TITLE
nginx or apache using version number

### ISSUE THREAD

**Issue by cedrox** [Azure/app-service-quickstart-docker-images#170]
Hello, 

### This issue is for a: (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [x ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

### Any log messages given by the failure
>Why are you using nginx since version 0.6 ?
A lot of work have been doing on this image using apache. Nginx can break a lot of optimisation work...

### Expected/desired behavior
>Maybe you should branch this and call it wordpress-alpine-php-apache and wordpress-alpine-php-nginx

Thanks

**Comment by LeonZhang77** [comment]
For now, we will keep using nginx with wordpress-alpine-php, since it's working better with Azure app service according to MS engineer's suggestion.

Your idea is great, if you like to keep use apache, you can create your own docker files.
Please feel free to create a new folder such as \wordpress-alpine-php-apache\0.1, it should be same as \wordpress-alpine-php\0.52, then create a PR to build-test branch, i will check and merge it, and built/push docker images.

**Comment by LeonZhang77** [comment]
below wordpress-apache-php images are pushed, they are using apache
https://hub.docker.com/r/appsvcorg/wordpress-apache-php/tags/

will keep using nginx with wordpress-alpine-php.
